mayavi2 -d iso.vtk \
 -m Outline \
 -s "actor.property.color = (1,0,0)"  \
 -s "actor.property.opacity = 1.0"    \
 -s "scene.background = (1,1,1)"      \
 -s "scene.camera.azimuth(60)"        \
 -s "scene.camera.elevation(20)"    \
 -s "scene.camera.zoom(1.2)"          \
 -s "scene.camera.parallel_projection = False" \
 -m IsoSurface \
 -s "contour.contours = [0.30]"                                      \
 -s "actor.property.opacity = 0.9"                                \
 -s "module_manager.scalar_lut_manager.use_default_range = False" \
 -s "module_manager.scalar_lut_manager.data_range = [0.0,1.0]"    \
 -s "module_manager.scalar_lut_manager.lut_mode = 'jet'"          \
 -m IsoSurface \
 -s "contour.contours = [1]"                                       \
 -s "actor.property.opacity = 0.2"                                 \
 -s "module_manager.scalar_lut_manager.use_default_range = False"  \
 -s "module_manager.scalar_lut_manager.data_range = [0.0,1.0]"     \
 -s "module_manager.scalar_lut_manager.lut_mode = 'jet'"           \
 -m Streamline \
 -s "streamline_type = 'tube'"                        \
 -s "stream_tracer.integration_direction = 'both'"    \
 -s "stream_tracer.integrator_type = 'runge_kutta45'" \
 -s "tube_filter.number_of_sides = 10"                \
 -s "tube_filter.radius = 0.30"                       \
 -s "tube_filter.capping = True"                      \
 -s "seed.widget.center = 25.5, 25.5, 25.5"           \
 -s "seed.widget.radius = 24.0"                       \
 -s "seed.widget.theta_resolution = 12"               \
 -s "seed.widget.phi_resolution = 12"                 \
 -s "seed.widget.enabled = False"                     \
 -s "scene.save('testnew.png', size=(800,800))" \
&& -HUP (1) 
